/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_PMEncoder_DataProducer */

#ifndef _Included_org_apache_hadoop_raid_PMEncoder_DataProducer
#define _Included_org_apache_hadoop_raid_PMEncoder_DataProducer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
