/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_JRSDecoder_JRSRDecoder */

#ifndef _Included_org_apache_hadoop_raid_JRSDecoder_JRSRDecoder
#define _Included_org_apache_hadoop_raid_JRSDecoder_JRSRDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_JRSDecoder_JRSRDecoder
 * Method:    jrsDecode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III[II)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSDecoder_00024JRSRDecoder_jrsDecode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jint);
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSDecoder_00024JRSRDecoder_jrsDr
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jint);
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSDecoder_00024JRSRDecoder_jrsDrM
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
