/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_PMDecoder_PMRDecoder */

#ifndef _Included_org_apache_hadoop_raid_PMDecoder_PMRDecoder
#define _Included_org_apache_hadoop_raid_PMDecoder_PMRDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_PMDecoder_PMRDecoder
 * Method:    pmDecode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III[II)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_PMDecoder_00024PMRDecoder_pmDecode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jint);

#ifdef __cplusplus
}
#endif
#endif
