/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_IAOEncoder */

#ifndef _Included_org_apache_hadoop_raid_IAOEncoder
#define _Included_org_apache_hadoop_raid_IAOEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_IAOEncoder
 * Method:    iaoEncode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_IAOEncoder_iaoEncode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
