/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_server_datanode_PMBlockSender */

#ifndef _Included_org_apache_hadoop_hdfs_server_datanode_PMBlockSender
#define _Included_org_apache_hadoop_hdfs_server_datanode_PMBlockSender
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_hdfs_server_datanode_PMBlockSender_MIN_BUFFER_WITH_TRANSFERTO
#define org_apache_hadoop_hdfs_server_datanode_PMBlockSender_MIN_BUFFER_WITH_TRANSFERTO 65536L
/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_PMBlockSender
 * Method:    pmREncode
 * Signature: ([B[BIIII[ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_PMBlockSender_pmREncode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
