/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_PMEncoder_SeqByteBuffer */

#ifndef _Included_org_apache_hadoop_raid_PMEncoder_SeqByteBuffer
#define _Included_org_apache_hadoop_raid_PMEncoder_SeqByteBuffer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
