/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_JRSOEncoder */

#ifndef _Included_org_apache_hadoop_raid_JRSOEncoder
#define _Included_org_apache_hadoop_raid_JRSOEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_JRSOEncoder
 * Method:    jrsoEncode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSOEncoder_jrsoEncode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
