/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_server_datanode_DataXceiverServer */

#ifndef _Included_org_apache_hadoop_hdfs_server_datanode_DataXceiverServer
#define _Included_org_apache_hadoop_hdfs_server_datanode_DataXceiverServer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_DataXceiverServer
 * Method:    pminit
 * Signature: (IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_DataXceiverServer_pminit
  (JNIEnv *, jobject, jint, jint, jobject);

/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_DataXceiverServer
 * Method:    iainit
 * Signature: (IILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_DataXceiverServer_iainit
  (JNIEnv *, jobject, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
