/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_JRSDecoder_JRSStreamFactory */

#ifndef _Included_org_apache_hadoop_raid_JRSDecoder_JRSStreamFactory
#define _Included_org_apache_hadoop_raid_JRSDecoder_JRSStreamFactory
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
