/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_PMEncoder_PMMigrationEncoder */

#ifndef _Included_org_apache_hadoop_raid_PMEncoder_PMMigrationEncoder
#define _Included_org_apache_hadoop_raid_PMEncoder_PMMigrationEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_PMEncoder_PMMigrationEncoder
 * Method:    pmEncode
 * Signature: (Lorg/apache/hadoop/raid/PMEncoder/PMMigrationEncoder;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_PMEncoder_00024PMMigrationEncoder_pmEncode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
