/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_IAEncoder_IAMigrationEncoder */

#ifndef _Included_org_apache_hadoop_raid_IAEncoder_IAMigrationEncoder
#define _Included_org_apache_hadoop_raid_IAEncoder_IAMigrationEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_IAEncoder_IAMigrationEncoder
 * Method:    iaEncode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;IIILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_IAEncoder_00024IAMigrationEncoder_iaEncode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
