/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_hdfs_server_datanode_IABlockSender */

#ifndef _Included_org_apache_hadoop_hdfs_server_datanode_IABlockSender
#define _Included_org_apache_hadoop_hdfs_server_datanode_IABlockSender
#ifdef __cplusplus
extern "C" {
#endif
#undef org_apache_hadoop_hdfs_server_datanode_IABlockSender_MIN_BUFFER_WITH_TRANSFERTO
#define org_apache_hadoop_hdfs_server_datanode_IABlockSender_MIN_BUFFER_WITH_TRANSFERTO 65536L
/*
 * Class:     org_apache_hadoop_hdfs_server_datanode_IABlockSender
 * Method:    iaREncode
 * Signature: ([B[BIIII[ILjava/nio/ByteBuffer;)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_hdfs_server_datanode_IABlockSender_iaREncode
  (JNIEnv *, jobject, jbyteArray, jbyteArray, jint, jint, jint, jint, jintArray, jobject);

#ifdef __cplusplus
}
#endif
#endif
