/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_JRSDecoder_JRSRecoveryDecoder */

#ifndef _Included_org_apache_hadoop_raid_JRSDecoder_JRSRecoveryDecoder
#define _Included_org_apache_hadoop_raid_JRSDecoder_JRSRecoveryDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_JRSDecoder_JRSRecoveryDecoder
 * Method:    jrsDecode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III[IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSDecoder_00024JRSRecoveryDecoder_jrsDecode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jint, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
