/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_JRSEncoder_JRSMigrationEncoder */

#ifndef _Included_org_apache_hadoop_raid_JRSEncoder_JRSMigrationEncoder
#define _Included_org_apache_hadoop_raid_JRSEncoder_JRSMigrationEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_JRSEncoder_JRSMigrationEncoder
 * Method:    jrsEncode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_JRSEncoder_00024JRSMigrationEncoder_jrsEncode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
