/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_IADecoder_IADegradedReadDecoder */

#ifndef _Included_org_apache_hadoop_raid_IADecoder_IADegradedReadDecoder
#define _Included_org_apache_hadoop_raid_IADecoder_IADegradedReadDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_IADecoder_IADegradedReadDecoder
 * Method:    iaDecode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III[I[IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_IADecoder_00024IADegradedReadDecoder_iaDecode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jintArray, jint, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
