/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_PMDecoder_PMDegradedReadDecoder */

#ifndef _Included_org_apache_hadoop_raid_PMDecoder_PMDegradedReadDecoder
#define _Included_org_apache_hadoop_raid_PMDecoder_PMDegradedReadDecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_PMDecoder_PMDegradedReadDecoder
 * Method:    pmDecode
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III[I[IILjava/nio/ByteBuffer;Z)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_PMDecoder_00024PMDegradedReadDecoder_pmDecode
  (JNIEnv *, jobject, jobject, jobject, jint, jint, jint, jintArray, jintArray, jint, jobject, jboolean);

#ifdef __cplusplus
}
#endif
#endif
