/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_apache_hadoop_raid_IADecoder */

#ifndef _Included_org_apache_hadoop_raid_IADecoder
#define _Included_org_apache_hadoop_raid_IADecoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_apache_hadoop_raid_IADecoder
 * Method:    iaValidate
 * Signature: (III[I[I)V
 */
JNIEXPORT void JNICALL Java_org_apache_hadoop_raid_IADecoder_iaValidate
  (JNIEnv *, jobject, jint, jint, jint, jintArray, jintArray);

#ifdef __cplusplus
}
#endif
#endif
